# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ExportToMySQL.ui'
#
# Created: Thu Dec 31 13:25:29 2009
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ExportToMySQL(object):
    def setupUi(self, ExportToMySQL):
        ExportToMySQL.setObjectName("ExportToMySQL")
        ExportToMySQL.resize(462, 435)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ExportToMySQL.setWindowIcon(icon)
        self.buttonBox = QtGui.QDialogButtonBox(ExportToMySQL)
        self.buttonBox.setGeometry(QtCore.QRect(10, 390, 441, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.exportToMySQLDataCheckBox = QtGui.QGroupBox(ExportToMySQL)
        self.exportToMySQLDataCheckBox.setGeometry(QtCore.QRect(10, 20, 441, 141))
        self.exportToMySQLDataCheckBox.setCheckable(True)
        self.exportToMySQLDataCheckBox.setObjectName("exportToMySQLDataCheckBox")
        self.labelMySQLHost = QtGui.QLabel(self.exportToMySQLDataCheckBox)
        self.labelMySQLHost.setGeometry(QtCore.QRect(20, 40, 56, 16))
        self.labelMySQLHost.setObjectName("labelMySQLHost")
        self.mysqlHost = QtGui.QLineEdit(self.exportToMySQLDataCheckBox)
        self.mysqlHost.setGeometry(QtCore.QRect(100, 40, 131, 22))
        self.mysqlHost.setObjectName("mysqlHost")
        self.labelMySQLUsername = QtGui.QLabel(self.exportToMySQLDataCheckBox)
        self.labelMySQLUsername.setGeometry(QtCore.QRect(20, 70, 71, 16))
        self.labelMySQLUsername.setObjectName("labelMySQLUsername")
        self.mysqlUsername = QtGui.QLineEdit(self.exportToMySQLDataCheckBox)
        self.mysqlUsername.setGeometry(QtCore.QRect(100, 72, 131, 20))
        self.mysqlUsername.setObjectName("mysqlUsername")
        self.labelMySQLPassword = QtGui.QLabel(self.exportToMySQLDataCheckBox)
        self.labelMySQLPassword.setGeometry(QtCore.QRect(20, 100, 56, 16))
        self.labelMySQLPassword.setObjectName("labelMySQLPassword")
        self.mysqlPassword = QtGui.QLineEdit(self.exportToMySQLDataCheckBox)
        self.mysqlPassword.setGeometry(QtCore.QRect(100, 100, 131, 22))
        self.mysqlPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.mysqlPassword.setObjectName("mysqlPassword")
        self.labelMySQLPort = QtGui.QLabel(self.exportToMySQLDataCheckBox)
        self.labelMySQLPort.setGeometry(QtCore.QRect(270, 40, 31, 16))
        self.labelMySQLPort.setObjectName("labelMySQLPort")
        self.mysqlPort = QtGui.QSpinBox(self.exportToMySQLDataCheckBox)
        self.mysqlPort.setGeometry(QtCore.QRect(310, 40, 61, 24))
        self.mysqlPort.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mysqlPort.setMinimum(1)
        self.mysqlPort.setMaximum(999999999)
        self.mysqlPort.setObjectName("mysqlPort")
        self.mysqlDatabaseName = QtGui.QLineEdit(ExportToMySQL)
        self.mysqlDatabaseName.setGeometry(QtCore.QRect(90, 300, 131, 22))
        self.mysqlDatabaseName.setObjectName("mysqlDatabaseName")
        self.mysqlTableName = QtGui.QLineEdit(ExportToMySQL)
        self.mysqlTableName.setGeometry(QtCore.QRect(90, 340, 131, 22))
        self.mysqlTableName.setObjectName("mysqlTableName")
        self.labelTableName = QtGui.QLabel(ExportToMySQL)
        self.labelTableName.setGeometry(QtCore.QRect(10, 340, 71, 16))
        self.labelTableName.setObjectName("labelTableName")
        self.labelMySQLDatabaseName = QtGui.QLabel(ExportToMySQL)
        self.labelMySQLDatabaseName.setGeometry(QtCore.QRect(10, 300, 56, 16))
        self.labelMySQLDatabaseName.setObjectName("labelMySQLDatabaseName")
        self.line = QtGui.QFrame(ExportToMySQL)
        self.line.setGeometry(QtCore.QRect(10, 160, 441, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.exportToSQLFileCheckBox = QtGui.QGroupBox(ExportToMySQL)
        self.exportToSQLFileCheckBox.setGeometry(QtCore.QRect(10, 180, 441, 91))
        self.exportToSQLFileCheckBox.setCheckable(True)
        self.exportToSQLFileCheckBox.setObjectName("exportToSQLFileCheckBox")
        self.labelSQLFilename = QtGui.QLabel(self.exportToSQLFileCheckBox)
        self.labelSQLFilename.setGeometry(QtCore.QRect(20, 30, 91, 16))
        self.labelSQLFilename.setObjectName("labelSQLFilename")
        self.sqlFilename = QtGui.QLineEdit(self.exportToSQLFileCheckBox)
        self.sqlFilename.setGeometry(QtCore.QRect(100, 30, 261, 22))
        self.sqlFilename.setReadOnly(False)
        self.sqlFilename.setObjectName("sqlFilename")
        self.replaceFileContentCheckBox = QtGui.QCheckBox(self.exportToSQLFileCheckBox)
        self.replaceFileContentCheckBox.setGeometry(QtCore.QRect(100, 60, 151, 21))
        self.replaceFileContentCheckBox.setObjectName("replaceFileContentCheckBox")
        self.browseButton = QtGui.QPushButton(self.exportToSQLFileCheckBox)
        self.browseButton.setGeometry(QtCore.QRect(369, 30, 61, 27))
        self.browseButton.setObjectName("browseButton")
        self.line_2 = QtGui.QFrame(ExportToMySQL)
        self.line_2.setGeometry(QtCore.QRect(10, 270, 441, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.addDropDatabaseCheckBox = QtGui.QCheckBox(ExportToMySQL)
        self.addDropDatabaseCheckBox.setGeometry(QtCore.QRect(250, 300, 151, 21))
        self.addDropDatabaseCheckBox.setObjectName("addDropDatabaseCheckBox")
        self.addDropTableCheckBox = QtGui.QCheckBox(ExportToMySQL)
        self.addDropTableCheckBox.setGeometry(QtCore.QRect(250, 340, 131, 21))
        self.addDropTableCheckBox.setObjectName("addDropTableCheckBox")
        self.zoomFullButton = QtGui.QPushButton(ExportToMySQL)
        self.zoomFullButton.setGeometry(QtCore.QRect(150, 390, 111, 31))
        self.zoomFullButton.setObjectName("zoomFullButton")

        self.retranslateUi(ExportToMySQL)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ExportToMySQL.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ExportToMySQL.reject)
        QtCore.QMetaObject.connectSlotsByName(ExportToMySQL)

    def retranslateUi(self, ExportToMySQL):
        ExportToMySQL.setWindowTitle(QtGui.QApplication.translate("ExportToMySQL", "Export To MySQL", None, QtGui.QApplication.UnicodeUTF8))
        self.exportToMySQLDataCheckBox.setTitle(QtGui.QApplication.translate("ExportToMySQL", "Export to MySQL data", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMySQLHost.setText(QtGui.QApplication.translate("ExportToMySQL", "Host", None, QtGui.QApplication.UnicodeUTF8))
        self.mysqlHost.setToolTip(QtGui.QApplication.translate("ExportToMySQL", "MySQL host name. Default : localhost", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMySQLUsername.setText(QtGui.QApplication.translate("ExportToMySQL", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.mysqlUsername.setToolTip(QtGui.QApplication.translate("ExportToMySQL", "MySQL username. Default : root", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMySQLPassword.setText(QtGui.QApplication.translate("ExportToMySQL", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.mysqlPassword.setToolTip(QtGui.QApplication.translate("ExportToMySQL", "MySQL password. Default : empty", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMySQLPort.setText(QtGui.QApplication.translate("ExportToMySQL", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.mysqlPort.setToolTip(QtGui.QApplication.translate("ExportToMySQL", "MySQL port. Default : 3306", None, QtGui.QApplication.UnicodeUTF8))
        self.mysqlDatabaseName.setToolTip(QtGui.QApplication.translate("ExportToMySQL", "Database name", None, QtGui.QApplication.UnicodeUTF8))
        self.mysqlTableName.setToolTip(QtGui.QApplication.translate("ExportToMySQL", "Table name where data will be stored.", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTableName.setText(QtGui.QApplication.translate("ExportToMySQL", "Table name", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMySQLDatabaseName.setText(QtGui.QApplication.translate("ExportToMySQL", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.exportToSQLFileCheckBox.setTitle(QtGui.QApplication.translate("ExportToMySQL", "Export to SQL file", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSQLFilename.setText(QtGui.QApplication.translate("ExportToMySQL", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.sqlFilename.setToolTip(QtGui.QApplication.translate("ExportToMySQL", "Fullpath to the filename where queries will be stored.", None, QtGui.QApplication.UnicodeUTF8))
        self.replaceFileContentCheckBox.setToolTip(QtGui.QApplication.translate("ExportToMySQL", "Checked : Replace the contents with new contents.\n"
"Unchecked : Append its contents.", None, QtGui.QApplication.UnicodeUTF8))
        self.replaceFileContentCheckBox.setText(QtGui.QApplication.translate("ExportToMySQL", "Replace file contents", None, QtGui.QApplication.UnicodeUTF8))
        self.browseButton.setText(QtGui.QApplication.translate("ExportToMySQL", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.addDropDatabaseCheckBox.setToolTip(QtGui.QApplication.translate("ExportToMySQL", "Force to drop database if exists.", None, QtGui.QApplication.UnicodeUTF8))
        self.addDropDatabaseCheckBox.setText(QtGui.QApplication.translate("ExportToMySQL", "Add drop database", None, QtGui.QApplication.UnicodeUTF8))
        self.addDropTableCheckBox.setToolTip(QtGui.QApplication.translate("ExportToMySQL", "Force to drop table if exists.", None, QtGui.QApplication.UnicodeUTF8))
        self.addDropTableCheckBox.setText(QtGui.QApplication.translate("ExportToMySQL", "Add drop table", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomFullButton.setToolTip(QtGui.QApplication.translate("ExportToMySQL", "Zoom full the active layers", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomFullButton.setText(QtGui.QApplication.translate("ExportToMySQL", "Zoom Full", None, QtGui.QApplication.UnicodeUTF8))

